### ISSUE TITLE
cputemp module does not work for alternate cpus

### ISSUE THREAD

**Issue by campital** [thytom/dwmbar#16]
In the "cputemp" module, it looks for a line containing "Temp1" in the output of sensors. On my AMD CPU, the line starts with "Tdie". Here is the output of `sensors` for me:
`k10temp-pci-00c3
Adapter: PCI adapter
Vcore:         1.30 V
Vsoc:        838.00 mV
Tdie:         +38.9°C
Tctl:         +38.9°C
Icore:        20.00 A
Isoc:          5.25 A`

**Comment by thytom** [comment]
Because the output of `sensors` varies so much between hardware (depending on cpu type, drivers installed, etc.), I'm hesitant to make changes to the default script, as while it might fix the problem for you, it could break the script for someone else.

The best solution for you would be to copy the `cputemp` script (located in `/usr/share/dwmbar/modules` to `~/.config/dwmbar/modules/custom`, where it will override the default and not be affected by any updates (which, to be honest, aren't likely). From there, you can edit it to grep for `Tdie` instead.
