### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by BioWare** [thytom/dwmbar#35]
which fonts are used here?? i can't display any icon from modules

**Comment by thytom** [comment]
You need a font that supports the icons. https://github.com/ryanoasis/nerd-fonts might have the one you're already using, if not, it also has a utility that lets you take the .otf/.ttf and patch it with the icons yourself.

Dwmbar just puts the text on the screen, it's been a while since I've done any DWM stuff myself so I don't actually remember how you set the font of the statusbar.

**Comment by BioWare** [comment]
> You need a font that supports the icons.

Thanks for answer. I already have patchet nerd-font. Seems like i need to set font on status bar. Thanks again
